name: alpine-rust
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 14 * * 0,2,4'
  push:
    branches:
    - main
    paths:
      - 'alpine-rust/*'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: build runner
      run: |
        docker build -t eu.gcr.io/downtozero/gh-alpine-rust -t cr.dtz.rocks/gh-alpine-rust -f alpine-rust/Dockerfile .
    - name: Login to cr.dtz.rocks
      uses: docker/login-action@v3
      with:
        registry: cr.dtz.rocks
        username: apikey
        password: ${{ secrets.DTZ_API_KEY }}
    - name: uploading image
      timeout-minutes: 10
      run: |
        docker push cr.dtz.rocks/gh-alpine-rust:latest
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: eu.gcr.io
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_KEY }}
    - name: uploading image
      run: |
        docker push eu.gcr.io/downtozero/gh-alpine-rust:latest

