name: api
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: build api
      run: |
        docker build -t gh-runner .
    # - name: Login to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     registry: eu.gcr.io
    #     username: _json_key
    #     password: ${{ secrets.GCLOUD_SERVICE_KEY }}
    # - name: uploading image
    #   run: |
    #     TS=`date +"%Y%m%d%H%M"`
    #     BRANCH=${GITHUB_REF##*/}
    #     docker tag dtz-containers-api eu.gcr.io/downtozero/dtz-containers-api:$BRANCH-$TS
    #     docker push eu.gcr.io/downtozero/dtz-containers-api:$BRANCH-$TS
    #     docker tag dtz-containers-api eu.gcr.io/downtozero/dtz-containers-api:latest
    #     docker push eu.gcr.io/downtozero/dtz-containers-api:latest
