name: build
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: build runner
      run: |
        docker build -t gh-runner .
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: eu.gcr.io
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_KEY }}
    - name: uploading image
      run: |
        docker tag gh-runner eu.gcr.io/downtozero/gh-runner:latest
        docker push eu.gcr.io/downtozero/gh-runner:latest
