name: ubuntu-2204-rust-protoc
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - 'ubuntu-2204-rust-protoc/*'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: build runner
      run: |
        docker build -t d202c2e9.cr.dtz.dev/gh-ubuntu-2204-rust-protoc -f ubuntu-2204-rust-protoc/Dockerfile .
    - name: Login to d202c2e9.cr.dtz.dev
      uses: docker/login-action@v3
      with:
        registry: d202c2e9.cr.dtz.dev
        username: apikey
        password: ${{ secrets.DTZ_API_KEY }}
    - name: uploading image
      run: |
        docker push d202c2e9.cr.dtz.dev/gh-ubuntu-2204-rust-protoc:latest
