name: ubuntu-2204-rust
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 13 * * 0,2,4'
  push:
    branches:
    - main
    paths:
      - 'ubuntu-2204-rust/*'
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: build runner
      run: |
        docker build -t eu.gcr.io/downtozero/gh-ubuntu-2204-rust -f ubuntu-2204-rust/Dockerfile .
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: eu.gcr.io
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_KEY }}
    - name: uploading image
      run: |
        docker push eu.gcr.io/downtozero/gh-ubuntu-2204-rust:latest
